FAQ edits (new, single edit, delete) functionality, no validations
the-difference-engine/we-r-next-generation-web pull request #46
Opened 2018-05-08 00:15 UTC by JennaDalgety

Added faq edit/add new/delete functionality
- component for viewing all faqs and selecting which ones to edit or delete
- component for the editing of an faq
- component for adding a new faq
- message to user when new faq is successfully added, deleted or edited

- still need to add simple form validation (checking for empty form fields

2018-05-08 00:23 UTC, zachgarwood commented
@knightofknee & @jdjustdata please take a couple minutes to review, and leave suggestions if necessary or give it the 👍 if it looks good.

2018-05-08 23:24 UTC, zachgarwood requested changes
Great job! It just needs a little cleanup here and there.

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqAddNew.vue
> +import sessionUtils from '../sessionUtils';
This `sessionUtils` import isn't used in this file and should be removed.

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqAddNew.vue
> +      messages: null
Since `messages` is a boolean, I think the default value should be `false` instead of `null`.

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqAddNew.vue
> +              this.messages = null;
Since `messages` is a boolean, I think `messages` should be set to `false` here.

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqAddNew.vue
> +  }
If this code isn't necessary, I would delete the whole function instead of commenting it out.

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqAddNew.vue
> +</style>
Since there're no styles for this component, we can get rid of the `<style>` tags.

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqEdit.vue
> +
Personal opinion: I don't like unnecessary extra whitespace. (If you do, that's cool ... but I'm judging you a little. 😈 )

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqEdit.vue
> +import sessionUtils from '../sessionUtils';
It seems like `sessionUtils` isn't used in this file either.

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqEdit.vue
> +        that: this
`that` doesn't seem to be used, scrap it. 🗑

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqEdit.vue
> +      messages: null
See my comments above about making `messages` a true/false boolean (instead of true/null).

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqEdit.vue
> +</style>
We can get rid of this empty `<style>` tag.

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqEditSingle.vue
> +import sessionUtils from '../sessionUtils';
See my comments above about this `sessionUtils` import.

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqEditSingle.vue
> +      messages: null
See my comments above about making `messages` a real boolean.

2018-05-08 23:24 UTC, zachgarwood commented on src/components/faqEditSingle.vue
> +</style>
![Baleeted](http://i0.kym-cdn.com/entries/icons/original/000/017/316/S7xEtpr.jpg)

2018-05-10 01:12 UTC, JennaDalgety commented
So!  Did the edits suggested.  Thank you for the cleanup!  I added a wysiwyg (with a node module called vue2 Editor) for the faqEditSingle and faqAdd components, as well as updating error validations to not show the same ones multiple times.  Have another look?

2018-05-10 23:26 UTC, zachgarwood approved these changes

2018-05-11 01:49 UTC, knightofknee commented on src/components/faqEditSingle.vue
> +            setTimeout(() => {}, 3000);
use console.error or something for catch

2018-05-11 01:53 UTC, knightofknee approved these changes
The non-main edit components needed containers, some console logs can be removed. everything looks great!! high quality interface

2018-05-14 18:27 UTC, zachgarwood commented
@jdjustdata don't forget to add your review!

2018-05-15 01:24 UTC, jdaniel0x50 commented on src/components/faq.vue
> +      axios
It appears the main FAQ page does not require a user to be logged in to submit a new question. Is this desirable? Should we require only logged in users to submit a question?

2018-05-15 01:33 UTC, jdaniel0x50 approved these changes
I think this looks good - pending getting rid of unneeded console.logs

2018-05-15 01:33 UTC, jdjustdata commented on src/components/faqAddNew.vue
> +        console.log('session:', session);
if you're done - take out the console.logs

2018-05-17 23:41 UTC, merged