completed admin waiver edit page
the-difference-engine/we-r-next-generation-web pull request #48
Opened 2018-05-09 23:36 UTC by jdjustdata

Completed vue page for waiver edits (same page will edit camper waiver and volunteer waiver based on routing)

2018-05-10 01:30 UTC, spyeadon approved these changes
Hey looks good to me!

2018-05-10 23:23 UTC, zachgarwood requested changes

2018-05-10 23:23 UTC, zachgarwood commented on src/components/admin_waiver_edit.vue
> +            dataObj: dataObj
I don't see `dataObj` in the [request configuration options](https://github.com/axios/axios#request-config), did you mean `data`?

2018-05-11 00:31 UTC, jdjustdata commented on src/components/admin_waiver_edit.vue
> +            dataObj: dataObj
sounds good - I changed the key to 'data' here and on the backend route - it makes more sense to use this consistently

2018-05-11 01:17 UTC, spyeadon approved these changes
Makes sense

2018-05-14 18:24 UTC, zachgarwood approved these changes

2018-05-14 18:26 UTC, zachgarwood commented
@JennaDalgety don't forget to add your review!

2018-05-14 22:57 UTC, JennaDalgety commented
Ah!  Apologies.  Thought I had responded to this.  Looked great in the video chat last week and Zach's edit should be the icing on the cake!

2018-05-14 23:47 UTC, merged