Add success
the-difference-engine/we-r-next-generation-web pull request #55
Opened 2018-05-24 01:30 UTC by JennaDalgety

- cleaned up vue editor toolbar on faq and success components
- removed extraneous code from faq components
- added working success (add/edit/delete) components and functionality
- will add image uploading functionality to success edits/adds next

2018-05-25 01:23 UTC, knightofknee commented on src/components/successEdit.vue
> +            <input readonly type="text" class="form-control" v-model="successStory.about" v-bind:placeholder="successStory.about">
this should be a div like the below one. also consider having the max height be bigger, as longer stuff that gets cut off isn't terribly readable, and I don't see a big downside to having it bigger

2018-05-25 01:53 UTC, knightofknee approved these changes
looks good except that one text box not like the other, with my comment

2018-05-30 23:43 UTC, jdaniel0x50 requested changes
Looks good. I made some comments where there remain significant portions of code commented out - that should likely be removed if they are no longer needed. The most significant comment is to remove the api key from the code base - and pass it through the database and data layer so that it is not searchable on our open source github account

2018-05-30 23:43 UTC, jdjustdata commented on src/components/successAddNew.vue
> +        <!-- <div class="form-group row">
This <div> is commented out - should you just remove it?

2018-05-30 23:43 UTC, jdjustdata commented on src/components/successAddNew.vue
> +      // cloudinary: {
commented out - remove?

2018-05-30 23:43 UTC, jdjustdata commented on src/components/successAddNew.vue
> +      //   apiKey: '234871425639756',
definitely remove the api key -- this should not be on github!

2018-05-30 23:43 UTC, jdjustdata commented on src/components/successAddNew.vue
> +    // previewImage: function(event) {
also commented out?

2018-05-30 23:43 UTC, jdjustdata commented on src/components/successAddNew.vue
> +// submitImage: function(evt) {
also commented out

2018-05-31 02:02 UTC, merged