User delete
the-difference-engine/we-r-next-generation-web pull request #76
Opened 2018-08-13 23:43 UTC by JennaDalgety

Created member delete functionality for superAdmins

2018-08-14 01:46 UTC, mkirlin requested changes

2018-08-14 01:46 UTC, mkirlin commented on src/components/profile.vue
> +    // changeStatus: function(link) {
If this is unused, let's delete it.

2018-08-14 01:46 UTC, mkirlin commented on src/components/profile.vue
> +/* #sideBar {
Let's delete this rather than just commenting it out.

2018-08-14 01:46 UTC, mkirlin commented on src/components/profile.vue
> +/* .profileNav {
Same as above.

2018-08-20 23:59 UTC, JennaDalgety commented
Deleted all commented out code that duplicated the separate sidebar component

2018-08-21 00:42 UTC, closed without merging